// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/MessageService.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostMessageResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostMessageResponse) Reset()         { *m = PostMessageResponse{} }
func (m *PostMessageResponse) String() string { return proto.CompactTextString(m) }
func (*PostMessageResponse) ProtoMessage()    {}
func (*PostMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46bd39c3f57efa4a, []int{0}
}

func (m *PostMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMessageResponse.Unmarshal(m, b)
}
func (m *PostMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMessageResponse.Marshal(b, m, deterministic)
}
func (m *PostMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMessageResponse.Merge(m, src)
}
func (m *PostMessageResponse) XXX_Size() int {
	return xxx_messageInfo_PostMessageResponse.Size(m)
}
func (m *PostMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostMessageResponse proto.InternalMessageInfo

func (m *PostMessageResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Message struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	CreateTime           int64    `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	AuthorName           string   `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_46bd39c3f57efa4a, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Message) GetAuthorName() string {
	if m != nil {
		return m.AuthorName
	}
	return ""
}

func init() {
	proto.RegisterType((*PostMessageResponse)(nil), "PostMessageResponse")
	proto.RegisterType((*Message)(nil), "Message")
}

func init() { proto.RegisterFile("proto/MessageService.proto", fileDescriptor_46bd39c3f57efa4a) }

var fileDescriptor_46bd39c3f57efa4a = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0x95, 0xaa, 0x53, 0x10, 0x19, 0xa5, 0x84, 0x78, 0xb0, 0xf4, 0xd4, 0x4b, 0x37,
	0xa2, 0xe0, 0x37, 0x10, 0x4f, 0x8a, 0xa4, 0xde, 0xc3, 0xb6, 0x3c, 0x63, 0xc0, 0xed, 0x86, 0xdd,
	0x89, 0x7f, 0xbe, 0xbd, 0x74, 0x77, 0x23, 0x0a, 0xbd, 0xed, 0xbc, 0xf9, 0xbd, 0x65, 0x7e, 0x54,
	0x74, 0xce, 0x8a, 0x2d, 0x1f, 0xe1, 0xbd, 0x6e, 0xb0, 0x82, 0xfb, 0x68, 0x37, 0x50, 0x21, 0x2c,
	0x2e, 0x1b, 0x6b, 0x9b, 0x77, 0x94, 0x61, 0x5a, 0xf7, 0xaf, 0x25, 0x4c, 0x27, 0xdf, 0x71, 0x39,
	0x5f, 0xd2, 0xf9, 0xb3, 0xf5, 0x92, 0x8a, 0x15, 0x7c, 0x67, 0xb7, 0x1e, 0x3c, 0xa5, 0xb1, 0x17,
	0x2d, 0xbd, 0xcf, 0xb3, 0x59, 0xb6, 0x38, 0xa9, 0xd2, 0x34, 0xaf, 0xe9, 0x28, 0xa1, 0xcc, 0x74,
	0x28, 0xf8, 0x92, 0x04, 0x84, 0x37, 0x5f, 0xd1, 0x64, 0xe3, 0xa0, 0x05, 0xb5, 0xb4, 0x06, 0xf9,
	0xc1, 0x2c, 0x5b, 0x8c, 0x2a, 0x8a, 0xd1, 0x4b, 0x6b, 0xb0, 0x03, 0x74, 0x2f, 0x6f, 0xd6, 0xd5,
	0x5b, 0x6d, 0x90, 0x8f, 0x42, 0x97, 0x62, 0xf4, 0xa4, 0x0d, 0x6e, 0x3e, 0xe9, 0xf4, 0xbf, 0x04,
	0xdf, 0xd1, 0xd9, 0x03, 0x86, 0x03, 0x57, 0xe2, 0xa0, 0x0d, 0x4f, 0x55, 0x74, 0x52, 0x83, 0x93,
	0xba, 0xdf, 0x39, 0x15, 0xc7, 0x2a, 0x71, 0xd7, 0x19, 0x2f, 0x69, 0xf2, 0xc7, 0x8c, 0x7f, 0x57,
	0xc5, 0x85, 0xda, 0x63, 0xbc, 0x1e, 0x87, 0xaf, 0x6e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x41,
	0x10, 0x27, 0x97, 0x4a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageServiceClient interface {
	GetMessageStream(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MessageService_GetMessageStreamClient, error)
	PostMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*PostMessageResponse, error)
}

type messageServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessageServiceClient(cc *grpc.ClientConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) GetMessageStream(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MessageService_GetMessageStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MessageService_serviceDesc.Streams[0], "/MessageService/GetMessageStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageServiceGetMessageStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MessageService_GetMessageStreamClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type messageServiceGetMessageStreamClient struct {
	grpc.ClientStream
}

func (x *messageServiceGetMessageStreamClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageServiceClient) PostMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*PostMessageResponse, error) {
	out := new(PostMessageResponse)
	err := c.cc.Invoke(ctx, "/MessageService/PostMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
type MessageServiceServer interface {
	GetMessageStream(*empty.Empty, MessageService_GetMessageStreamServer) error
	PostMessage(context.Context, *Message) (*PostMessageResponse, error)
}

// UnimplementedMessageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (*UnimplementedMessageServiceServer) GetMessageStream(req *empty.Empty, srv MessageService_GetMessageStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMessageStream not implemented")
}
func (*UnimplementedMessageServiceServer) PostMessage(ctx context.Context, req *Message) (*PostMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMessage not implemented")
}

func RegisterMessageServiceServer(s *grpc.Server, srv MessageServiceServer) {
	s.RegisterService(&_MessageService_serviceDesc, srv)
}

func _MessageService_GetMessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageServiceServer).GetMessageStream(m, &messageServiceGetMessageStreamServer{stream})
}

type MessageService_GetMessageStreamServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type messageServiceGetMessageStreamServer struct {
	grpc.ServerStream
}

func (x *messageServiceGetMessageStreamServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _MessageService_PostMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PostMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessageService/PostMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PostMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostMessage",
			Handler:    _MessageService_PostMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMessageStream",
			Handler:       _MessageService_GetMessageStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/MessageService.proto",
}
